### ISSUE TITLE
PCB for S3_C6_NanoAP v2.2

### ISSUE THREAD

**Issue by LeftPinkie** [OpenEPaperLink/Hardware#3]
Does anyone know who designed PCB pictured in the S3_C6_NanoAP Case Variant 2 (case is made by: Viktor Knall)?
https://github.com/OpenEPaperLink/Hardware/blob/main/S3_C6_NanoAP%20Case/V2_2_Case_Image1_By_Viktor_Knall.png
https://github.com/OpenEPaperLink/Hardware/blob/main/S3_C6_NanoAP%20Case/V2_2_Case_Image_By_Viktor_Knall.png

I am looking for the PCB, not the case.

**Comment by atc1441** [comment]
Hey, this one is made by be, did never publish the PCB files, would advice to use the V1 AP https://github.com/OpenEPaperLink/Hardware/tree/main/S3_C6_NanoAP%20by%20ATC1441
The changes in V2 are only the form factor but not in the Schematics or function
