### ISSUE TITLE
Feature request: CPL file for Flasher cable by Nic

### ISSUE THREAD

**Issue by DJBenson** [OpenEPaperLink/Hardware#6]
Does anybody have the CPL file for the associated gerber file? It's specifically the v1.3 gerber file I'm ordering.

The repo contains almost everything someone who is rubbish at soldering (like me) needs to order a fully built cable from JLCPCB - the gerber file, the BOM but not the CPL file which JLCPCB needs to do the build.

Thanks in advance.

**Comment by nlimper** [comment]
I added a new version, including pick and place file.
https://github.com/OpenEPaperLink/Hardware/tree/main/Flasher%20cable%20by%20Nic
